// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var match = true;

var discount = match ? 0.05 : 0.10;

var total = 7 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("Prix avant xxxxx:" + (total.toString() + "€"));

console.log("Prix avant xxxxx" + (total.toString() + "\xe2\x82\xac"));

var qty = 7;

var price = 14.50;

var str = "doorbell";

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
exports.str = str;
/*  Not a pure module */
