// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function calcPercent(score, max) {
  return /* Percent */[score[0] / max[0] * 100.0];
}

var match = calcPercent(/* Score */[40], /* Score */[75]);

var person = /* UserId */[60];

var result = match[0];

exports.person = person;
exports.calcPercent = calcPercent;
exports.result = result;
/* match Not a pure module */
