# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78262cd07c4e8b726ec4cecd80d38148d430da8913320075415a156180b3f8329e84f76c4891dab0e2ca6f560bf9640a0bf8427edbd2a4b3128e87f5e3e2c1b1

test:
  secret_key_base: bd741ad93b914065193aea4b844939134ceac232d3fe2b44d1f94c82cdc23fea53dfbe52a1a81fcc8d192577c760add59206e492d17098d5ee0803e269784307

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
